name: ðŸªƒ Cron - Update dependencies

on:
  workflow_dispatch:

jobs:
  update:
    strategy:
      matrix:
        node-version: [20.x]

    name: ðŸ†’ Update all dependencies
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci --legacy-peer-deps

      - run: npx npm-check-updates -u # Update dependencies
      - run: rm -Rf node_modules package-lock.json
      - run: npm install --legacy-peer-deps
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "build: ðŸ“¦ update dependencies to the latest version"
          title: Update dependencies to the latest version
          body: |
            Dependencies automatically updated to the latest version!
            Ignoring ranges specified
            - [x] Dependencies updated
            - [ ] Tests passed
            - [ ] Review
            Please review the changes and merge this Pull Request if it looks good.
          branch: chore/PR-000-npm-update-dependencies-latest
          delete-branch: true
          branch-suffix: timestamp
